name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { name: Windows MSVC, os: windows-latest }
          - { name: Linux GCC,    os: ubuntu-latest }
          - { name: macOS Clang,  os: macos-latest }

    steps:
      - uses: actions/checkout@v4
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libxi-dev libudev-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype-dev
      - run: cmake -B Build
      - run: cmake --build Build -j